function template(locals) {
var jade_debug = [ new jade.DebugItem( 1, "index.jade" ) ];
try {
var buf = [];
var jade_mixins = {};
var jade_interp;

jade_debug.unshift(new jade.DebugItem( 0, "index.jade" ));
jade_debug.unshift(new jade.DebugItem( 1, "index.jade" ));
buf.push("<!DOCTYPE html>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 2, "index.jade" ));
buf.push("<html>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 3, "index.jade" ));
buf.push("<head>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 4, "index.jade" ));
buf.push("<title>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 4, jade_debug[0].filename ));
buf.push("Untangling the Hairball");
jade_debug.shift();
jade_debug.shift();
buf.push("</title>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 5, "index.jade" ));
buf.push("<link rel=\"stylesheet\" href=\"css/reveal.css\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 6, "index.jade" ));
buf.push("<link rel=\"stylesheet\" href=\"css/theme/white.css\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 7, "index.jade" ));
buf.push("<link rel=\"stylesheet\" href=\"css/main.css\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 8, "index.jade" ));
buf.push("<link rel=\"stylesheet\" href=\"css/scrollable.css\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 9, "index.jade" ));
buf.push("<link rel=\"stylesheet\" href=\"css/scrollableHairball.css\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 10, "index.jade" ));
buf.push("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Oswald|Quattrocento\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 12, "index.jade" ));
buf.push("<meta charset=\"utf-8\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 13, "index.jade" ));
buf.push("<meta name=\"author\" content=\"Deisy Díaz, John Alexis Guerra Gomez\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 14, "index.jade" ));
buf.push("<meta name=\"description\" content=\"Kangaroo Babies\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 15, "index.jade" ));
buf.push("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 17, "index.jade" ));
buf.push("<style>");
jade_debug.unshift(new jade.DebugItem( 27, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 27, jade_debug[0].filename ));
buf.push(".reveal h1,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 27, jade_debug[0].filename ));
buf.push(".reveal h2,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 27, jade_debug[0].filename ));
buf.push(".reveal h3,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 27, jade_debug[0].filename ));
buf.push(".reveal h4 {");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 27, jade_debug[0].filename ));
buf.push("  font-family: 'Oswald', serif;");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 27, jade_debug[0].filename ));
buf.push("}");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 27, jade_debug[0].filename ));
buf.push(".reveal {");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 27, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 27, jade_debug[0].filename ));
buf.push("  font-family: 'Quattrocento', sans-serif;");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 27, jade_debug[0].filename ));
buf.push("}");
jade_debug.shift();
jade_debug.shift();
buf.push("</style>");
jade_debug.shift();
jade_debug.shift();
buf.push("</head>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 28, "index.jade" ));
buf.push("<body>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 30, "index.jade" ));
buf.push("<div class=\"reveal\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 31, "index.jade" ));
buf.push("<div class=\"slides\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 33, "index.jade" ));
buf.push("<div class=\"scrollable scrollable-hairball\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 34, "index.jade" ));
buf.push("<div id=\"networkChartHair\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 36, "index.jade" ));
buf.push("<div class=\"scrollable scrollable-tips\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 37, "index.jade" ));
buf.push("<div id=\"networkChartTips\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 39, "index.jade" ));
buf.push("<section>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 40, "index.jade" ));
buf.push("<section>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 41, "index.jade" ));
buf.push("<h1>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 41, jade_debug[0].filename ));
buf.push("Kangaroo Babies");
jade_debug.shift();
jade_debug.shift();
buf.push("</h1>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 43, "index.jade" ));
buf.push("<p class=\"authors\">");
jade_debug.unshift(new jade.DebugItem( 47, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 47, jade_debug[0].filename ));
buf.push("Deisy Díazzzzz");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 0, "index.jade" ));
jade_debug.unshift(new jade.DebugItem( 1, "index.jade" ));
buf.push("<sup>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 1, jade_debug[0].filename ));
buf.push("&dagger;");
jade_debug.shift();
jade_debug.shift();
buf.push("</sup>");
jade_debug.shift();
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 47, jade_debug[0].filename ));
buf.push(", ");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 0, "index.jade" ));
jade_debug.unshift(new jade.DebugItem( 1, "index.jade" ));
buf.push("<a href=\"http://johnguerra.co/\" target=\"_blank\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 1, jade_debug[0].filename ));
buf.push("John A. Guerra Gómez");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 47, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 0, "index.jade" ));
jade_debug.unshift(new jade.DebugItem( 1, "index.jade" ));
buf.push("<sup>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 1, jade_debug[0].filename ));
buf.push("&dagger;");
jade_debug.shift();
jade_debug.shift();
buf.push("</sup>");
jade_debug.shift();
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 47, jade_debug[0].filename ));
buf.push(", Julieta");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 0, "index.jade" ));
jade_debug.unshift(new jade.DebugItem( 1, "index.jade" ));
buf.push("<sup>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 1, jade_debug[0].filename ));
buf.push("&Dagger;");
jade_debug.shift();
jade_debug.shift();
buf.push("</sup>");
jade_debug.shift();
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 47, jade_debug[0].filename ));
buf.push(", Nathalie");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 0, "index.jade" ));
jade_debug.unshift(new jade.DebugItem( 1, "index.jade" ));
buf.push("<sup>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 1, jade_debug[0].filename ));
buf.push("&Dagger;");
jade_debug.shift();
jade_debug.shift();
buf.push("</sup>");
jade_debug.shift();
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 47, jade_debug[0].filename ));
buf.push(", Tiberio");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 0, "index.jade" ));
jade_debug.unshift(new jade.DebugItem( 1, "index.jade" ));
buf.push("<sup>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 1, jade_debug[0].filename ));
buf.push("&dagger;");
jade_debug.shift();
jade_debug.shift();
buf.push("</sup>");
jade_debug.shift();
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 47, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 47, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 0, "index.jade" ));
jade_debug.unshift(new jade.DebugItem( 1, "index.jade" ));
buf.push("<br>");
jade_debug.shift();
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 47, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 47, jade_debug[0].filename ));
buf.push("Los Andes University");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 0, "index.jade" ));
jade_debug.unshift(new jade.DebugItem( 1, "index.jade" ));
buf.push("<sup>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 1, jade_debug[0].filename ));
buf.push("&dagger;");
jade_debug.shift();
jade_debug.shift();
buf.push("</sup>");
jade_debug.shift();
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 47, jade_debug[0].filename ));
buf.push(" and Kangaroo Foundation");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 0, "index.jade" ));
jade_debug.unshift(new jade.DebugItem( 1, "index.jade" ));
buf.push("<sup>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 1, jade_debug[0].filename ));
buf.push("&Dagger;");
jade_debug.shift();
jade_debug.shift();
buf.push("</sup>");
jade_debug.shift();
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 47, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 47, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 48, "index.jade" ));
buf.push("<p class=\"tiny\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 49, "index.jade" ));
buf.push("<a href=\"http://johnguerra.co/slides/kangarooBabies\" target=\"_blank\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 49, jade_debug[0].filename ));
buf.push("http://johnguerra.co/slides/kangarooBabies");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 51, "index.jade" ));
buf.push("<div class=\"left logo\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 52, "index.jade" ));
buf.push("<a href=\"http://www.uniandes.edu.co/\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 53, "index.jade" ));
buf.push("<img src=\"images/universidad_de_los_andes_logo@2x.png\" alt=\"Los Andes University\" class=\"logo\">");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 54, "index.jade" ));
buf.push("<div class=\"right logo\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 55, "index.jade" ));
buf.push("<a href=\"https://datascience.berkeley.edu/\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 56, "index.jade" ));
buf.push("<img src=\"images/UC_Berkeley_wordmark_cal_gold.png\" alt=\"Kangaroo Foundation Logo\" class=\"logo\">");
jade_debug.shift();
jade_debug.shift();
buf.push("</a>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 59, "index.jade" ));
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 59, "index.jade" ));
buf.push("<section>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 60, "index.jade" ));
buf.push("<section>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 61, "index.jade" ));
buf.push("<h1>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 61, jade_debug[0].filename ));
buf.push("4 steps Model");
jade_debug.shift();
jade_debug.shift();
buf.push("</h1>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 63, "index.jade" ));
buf.push("<section>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 64, "index.jade" ));
buf.push("<h2>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 64, jade_debug[0].filename ));
buf.push("Time based events");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 66, "index.jade" ));
buf.push("<ul>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 67, "index.jade" ));
buf.push("<li class=\"fragment\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 67, jade_debug[0].filename ));
buf.push("Presidential election");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 68, "index.jade" ));
buf.push("<li class=\"fragment\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 68, jade_debug[0].filename ));
buf.push("Presidential election");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 69, "index.jade" ));
buf.push("<li class=\"fragment\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 69, jade_debug[0].filename ));
buf.push("Presidential election");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.shift();
buf.push("</ul>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 71, "index.jade" ));
buf.push("<section>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 72, "index.jade" ));
buf.push("<h2>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 72, jade_debug[0].filename ));
buf.push("4 steps Model");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 73, "index.jade" ));
buf.push("<p>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 73, jade_debug[0].filename ));
buf.push("Diagram model");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 75, "index.jade" ));
buf.push("<section>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 76, "index.jade" ));
buf.push("<h2>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 76, jade_debug[0].filename ));
buf.push("Example applications");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 77, "index.jade" ));
buf.push("<p>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 77, jade_debug[0].filename ));
buf.push("Applying the model to the problems");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 80, "index.jade" ));
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 80, "index.jade" ));
buf.push("<section>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 81, "index.jade" ));
buf.push("<section>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 82, "index.jade" ));
buf.push("<h1>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 82, jade_debug[0].filename ));
buf.push("Kangaroo");
jade_debug.shift();
jade_debug.shift();
buf.push("</h1>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 84, "index.jade" ));
buf.push("<section>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 85, "index.jade" ));
buf.push("<h2>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 85, jade_debug[0].filename ));
buf.push("The problem");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 87, "index.jade" ));
buf.push("<section>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 88, "index.jade" ));
buf.push("<h2>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 88, jade_debug[0].filename ));
buf.push("Kangaroo Foundation");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 90, "index.jade" ));
buf.push("<section>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 91, "index.jade" ));
buf.push("<h2>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 91, jade_debug[0].filename ));
buf.push("The Experts");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 93, "index.jade" ));
buf.push("<section>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 94, "index.jade" ));
buf.push("<h2>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 94, jade_debug[0].filename ));
buf.push("The Data");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 96, "index.jade" ));
buf.push("<section>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 97, "index.jade" ));
buf.push("<h2>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 97, jade_debug[0].filename ));
buf.push("The Tasks");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 99, "index.jade" ));
buf.push("<section>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 100, "index.jade" ));
buf.push("<h2>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 100, jade_debug[0].filename ));
buf.push("Insights");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 103, "index.jade" ));
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 103, "index.jade" ));
buf.push("<section>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 104, "index.jade" ));
buf.push("<section>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 105, "index.jade" ));
buf.push("<h1>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 105, jade_debug[0].filename ));
buf.push("Viz");
jade_debug.shift();
jade_debug.shift();
buf.push("</h1>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 107, "index.jade" ));
buf.push("<section>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 108, "index.jade" ));
buf.push("<h2>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 108, jade_debug[0].filename ));
buf.push("Femton 1 child");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 109, "index.jade" ));
buf.push("<section>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 110, "index.jade" ));
buf.push("<h2>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 110, jade_debug[0].filename ));
buf.push("Femton 10k children");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 111, "index.jade" ));
buf.push("<section>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 112, "index.jade" ));
buf.push("<h2>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 112, jade_debug[0].filename ));
buf.push("+ OMS");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 113, "index.jade" ));
buf.push("<section>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 114, "index.jade" ));
buf.push("<h2>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 114, jade_debug[0].filename ));
buf.push("Normalization");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 116, "index.jade" ));
buf.push("<section>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 117, "index.jade" ));
buf.push("<h2>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 117, jade_debug[0].filename ));
buf.push("Our viz");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 119, "index.jade" ));
buf.push("<section>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 120, "index.jade" ));
buf.push("<section>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 121, "index.jade" ));
buf.push("<h3 class=\"demo\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 121, jade_debug[0].filename ));
buf.push("Thank you!");
jade_debug.shift();
jade_debug.shift();
buf.push("</h3>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 122, "index.jade" ));
buf.push("<div class=\"left\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 123, "index.jade" ));
buf.push("<ul>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 124, "index.jade" ));
buf.push("<li>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 124, jade_debug[0].filename ));
buf.push("Model");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 125, "index.jade" ));
buf.push("<li>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 125, jade_debug[0].filename ));
buf.push("Viz");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 126, "index.jade" ));
buf.push("<li>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 126, jade_debug[0].filename ));
buf.push("Use case (Insights)");
jade_debug.shift();
jade_debug.shift();
buf.push("</li>");
jade_debug.shift();
jade_debug.shift();
buf.push("</ul>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 127, "index.jade" ));
buf.push("<div class=\"right\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 128, "index.jade" ));
buf.push("<p>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 128, jade_debug[0].filename ));
buf.push("Video demo");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.shift();
buf.push("</section>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 132, "index.jade" ));
buf.push("<script src=\"js/head.min.js\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 133, "index.jade" ));
buf.push("<script src=\"js/reveal.js\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 134, "index.jade" ));
buf.push("<script src=\"js/d3.v4.min.js\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 135, "index.jade" ));
buf.push("<script src=\"js/networkCanvasChart.js\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 136, "index.jade" ));
buf.push("<script src=\"js/netClustering.js\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 137, "index.jade" ));
buf.push("<script src=\"js/forceInABoxv4.js\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 138, "index.jade" ));
buf.push("<script src=\"js/ScrollableHairball.js\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 139, "index.jade" ));
buf.push("<script src=\"js/ScrollableTips.js\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 140, "index.jade" ));
buf.push("<script src=\"js/makeScrollable.js\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 142, "index.jade" ));
buf.push("<script>");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("Reveal.initialize({");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // Display controls in the bottom right corner");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  controls: true,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // Display a presentation progress bar");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  progress: true,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // Display the page number of the current slide");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  slideNumber: false,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // Push each slide change to the browser history");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  history: true,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // Enable keyboard shortcuts for navigation");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  keyboard: true,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // Enable the slide overview mode");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  overview: true,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // Vertical centering of slides");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  center: true,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // Enables touch navigation on devices with touch input");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  touch: true,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // Loop the presentation");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  loop: false,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // Change the presentation direction to be RTL");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  rtl: false,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // Randomizes the order of slides each time the presentation loads");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  shuffle: false,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // Turns fragments on and off globally");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  fragments: true,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // Flags if the presentation is running in an embedded mode,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // i.e. contained within a limited portion of the screen");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  embedded: false,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // Flags if we should show a help overlay when the questionmark");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // key is pressed");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  help: true,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // Flags if speaker notes should be visible to all viewers");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  showNotes: false,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // Number of milliseconds between automatically proceeding to the");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // next slide, disabled when set to 0, this value can be overwritten");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // by using a data-autoslide attribute on your slides");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  autoSlide: 0,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // Stop auto-sliding after user input");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  autoSlideStoppable: true,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // Use this method for navigation when auto-sliding");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  autoSlideMethod: Reveal.navigateNext,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // Enable slide navigation via mouse wheel");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  mouseWheel: false,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // Hides the address bar on mobile devices");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  hideAddressBar: true,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // Opens links in an iframe preview overlay");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  previewLinks: false,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // Transition style");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  transition: 'slide', // none/fade/slide/convex/concave/zoom");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // Transition speed");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  transitionSpeed: 'default', // default/fast/slow");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // Transition style for full page slide backgrounds");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  backgroundTransition: 'fade', // none/fade/slide/convex/concave/zoom");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // Number of slides away from the current that are visible");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  viewDistance: 3,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // Parallax background image");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  parallaxBackgroundImage: '', // e.g. \"'https://s3.amazonaws.com/hakim-static/reveal-js/reveal-parallax-1.jpg'\"");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // Parallax background size");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  parallaxBackgroundSize: '', // CSS syntax, e.g. \"2100px 900px\"");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // Number of pixels to move the parallax background per slide");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // - Calculated automatically unless specified");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // - Set to 0 to disable movement along an axis");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  parallaxBackgroundHorizontal: null,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  parallaxBackgroundVertical: null,");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // Options which are passed into marked");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  // See https://github.com/chjj/marked#options-1");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  markdown: {");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("    smartypants: true");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  },");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  dependencies: [");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("    // Cross-browser shim that fully implements classList - https://github.com/eligrey/classList.js/");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("    { src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("    // Interpret Markdown in <section> elements");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("    { src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("    { src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("    // Syntax highlight for <code> elements");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("    { src: 'plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("    // Zoom in and out with Alt+click");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("    { src: 'plugin/zoom-js/zoom.js', async: true },");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("    // Speaker notes");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("    { src: 'plugin/notes/notes.js', async: true },");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("    // MathJax");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("    { src: 'plugin/math/math.js', async: true }");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("  ],");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("});");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 263, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 265, "index.jade" ));
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 265, "index.jade" ));
buf.push("<script>");
jade_debug.unshift(new jade.DebugItem( 274, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 274, jade_debug[0].filename ));
buf.push("(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 274, jade_debug[0].filename ));
buf.push("(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 274, jade_debug[0].filename ));
buf.push("m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 274, jade_debug[0].filename ));
buf.push("})(window,document,'script','//www.google-analytics.com/analytics.js','ga');");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 274, jade_debug[0].filename ));
buf.push("");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 274, jade_debug[0].filename ));
buf.push("ga('create', 'UA-72531610-1', 'auto');");
jade_debug.shift();
buf.push("\n");
jade_debug.unshift(new jade.DebugItem( 274, jade_debug[0].filename ));
buf.push("ga('send', 'pageview');");
jade_debug.shift();
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.shift();
buf.push("</body>");
jade_debug.shift();
jade_debug.shift();
buf.push("</html>");
jade_debug.shift();
jade_debug.shift();;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade_debug[0].filename, jade_debug[0].lineno, "doctype html\r\nhtml\r\n  head\r\n    title Untangling the Hairball\r\n    link(rel=\"stylesheet\", href=\"css/reveal.css\")\r\n    link(rel=\"stylesheet\", href=\"css/theme/white.css\")\r\n    link(rel=\"stylesheet\", href=\"css/main.css\")\r\n    link(rel=\"stylesheet\", href=\"css/scrollable.css\")\r\n    link(rel=\"stylesheet\", href=\"css/scrollableHairball.css\")\r\n    link(rel=\"stylesheet\", href=\"https://fonts.googleapis.com/css?family=Oswald|Quattrocento\")\r\n\r\n    meta(charset='utf-8')\r\n    meta(name='author', content='Deisy Díaz, John Alexis Guerra Gomez')\r\n    meta(name='description', content=\"Kangaroo Babies\")\r\n    meta(name=\"viewport\",content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui\")\r\n\r\n    style.\r\n      .reveal h1,\r\n      .reveal h2,\r\n      .reveal h3,\r\n      .reveal h4 {\r\n        font-family: 'Oswald', serif;\r\n      }\r\n      .reveal {\r\n\r\n        font-family: 'Quattrocento', sans-serif;\r\n      }\r\n  body\r\n\r\n    div.reveal\r\n      div.slides\r\n\r\n        div.scrollable.scrollable-hairball\r\n          div#networkChartHair\r\n\r\n        div.scrollable.scrollable-tips\r\n          div#networkChartTips\r\n\r\n        section\r\n          section\r\n            h1 Kangaroo Babies\r\n\r\n            p.authors.\r\n              Deisy Díazzzzz#[sup &dagger;], #[a(href='http://johnguerra.co/', target='_blank') John A. Guerra Gómez]#[sup &dagger;], Julieta#[sup &Dagger;], Nathalie#[sup &Dagger;], Tiberio#[sup &dagger;]\r\n              #[br]\r\n              Los Andes University#[sup &dagger;] and Kangaroo Foundation#[sup &Dagger;]\r\n\r\n            p.tiny\r\n              a(href='http://johnguerra.co/slides/kangarooBabies', target='_blank') http://johnguerra.co/slides/kangarooBabies\r\n\r\n            div.left.logo\r\n              a(href=\"http://www.uniandes.edu.co/\")\r\n                img.logo(src=\"images/universidad_de_los_andes_logo@2x.png\" alt=\"Los Andes University\")\r\n            div.right.logo\r\n              a(href=\"https://datascience.berkeley.edu/\")\r\n                img.logo(src=\"images/UC_Berkeley_wordmark_cal_gold.png\" alt=\"Kangaroo Foundation Logo\")\r\n\r\n        //- #########################  The model\r\n        section\r\n          section\r\n            h1 4 steps Model\r\n\r\n          section\r\n            h2 Time based events\r\n\r\n            ul\r\n              li.fragment Presidential election\r\n              li.fragment Presidential election\r\n              li.fragment Presidential election\r\n\r\n          section\r\n            h2 4 steps Model\r\n            p Diagram model\r\n\r\n          section\r\n            h2 Example applications\r\n            p Applying the model to the problems\r\n\r\n        //- #########################  Kangaroo\r\n        section\r\n          section\r\n            h1 Kangaroo\r\n\r\n          section\r\n            h2 The problem\r\n\r\n          section\r\n            h2 Kangaroo Foundation\r\n\r\n          section\r\n            h2 The Experts\r\n\r\n          section\r\n            h2 The Data\r\n\r\n          section\r\n            h2 The Tasks\r\n\r\n          section\r\n            h2 Insights\r\n\r\n        //- #########################  The viz\r\n        section\r\n          section\r\n            h1 Viz\r\n\r\n          section\r\n            h2 Femton 1 child\r\n          section\r\n            h2 Femton 10k children\r\n          section\r\n            h2 + OMS\r\n          section\r\n            h2 Normalization\r\n\r\n          section\r\n            h2 Our viz\r\n\r\n        section\r\n          section\r\n            h3.demo Thank you!\r\n            div.left\r\n              ul\r\n                li Model\r\n                li Viz\r\n                li Use case (Insights)\r\n            div.right\r\n              p Video demo\r\n\r\n\r\n\r\n    script(src=\"js/head.min.js\")\r\n    script(src=\"js/reveal.js\")\r\n    script(src=\"js/d3.v4.min.js\")\r\n    script(src=\"js/networkCanvasChart.js\")\r\n    script(src=\"js/netClustering.js\")\r\n    script(src=\"js/forceInABoxv4.js\")\r\n    script(src=\"js/ScrollableHairball.js\")\r\n    script(src=\"js/ScrollableTips.js\")\r\n    script(src=\"js/makeScrollable.js\")\r\n\r\n    script.\r\n      Reveal.initialize({\r\n        // Display controls in the bottom right corner\r\n        controls: true,\r\n\r\n        // Display a presentation progress bar\r\n        progress: true,\r\n\r\n        // Display the page number of the current slide\r\n        slideNumber: false,\r\n\r\n        // Push each slide change to the browser history\r\n        history: true,\r\n\r\n        // Enable keyboard shortcuts for navigation\r\n        keyboard: true,\r\n\r\n        // Enable the slide overview mode\r\n        overview: true,\r\n\r\n        // Vertical centering of slides\r\n        center: true,\r\n\r\n        // Enables touch navigation on devices with touch input\r\n        touch: true,\r\n\r\n        // Loop the presentation\r\n        loop: false,\r\n\r\n        // Change the presentation direction to be RTL\r\n        rtl: false,\r\n\r\n        // Randomizes the order of slides each time the presentation loads\r\n        shuffle: false,\r\n\r\n        // Turns fragments on and off globally\r\n        fragments: true,\r\n\r\n        // Flags if the presentation is running in an embedded mode,\r\n        // i.e. contained within a limited portion of the screen\r\n        embedded: false,\r\n\r\n        // Flags if we should show a help overlay when the questionmark\r\n        // key is pressed\r\n        help: true,\r\n\r\n        // Flags if speaker notes should be visible to all viewers\r\n        showNotes: false,\r\n\r\n        // Number of milliseconds between automatically proceeding to the\r\n        // next slide, disabled when set to 0, this value can be overwritten\r\n        // by using a data-autoslide attribute on your slides\r\n        autoSlide: 0,\r\n\r\n        // Stop auto-sliding after user input\r\n        autoSlideStoppable: true,\r\n\r\n        // Use this method for navigation when auto-sliding\r\n        autoSlideMethod: Reveal.navigateNext,\r\n\r\n        // Enable slide navigation via mouse wheel\r\n        mouseWheel: false,\r\n\r\n        // Hides the address bar on mobile devices\r\n        hideAddressBar: true,\r\n\r\n        // Opens links in an iframe preview overlay\r\n        previewLinks: false,\r\n\r\n        // Transition style\r\n        transition: 'slide', // none/fade/slide/convex/concave/zoom\r\n\r\n        // Transition speed\r\n        transitionSpeed: 'default', // default/fast/slow\r\n\r\n        // Transition style for full page slide backgrounds\r\n        backgroundTransition: 'fade', // none/fade/slide/convex/concave/zoom\r\n\r\n        // Number of slides away from the current that are visible\r\n        viewDistance: 3,\r\n\r\n        // Parallax background image\r\n        parallaxBackgroundImage: '', // e.g. \"'https://s3.amazonaws.com/hakim-static/reveal-js/reveal-parallax-1.jpg'\"\r\n\r\n        // Parallax background size\r\n        parallaxBackgroundSize: '', // CSS syntax, e.g. \"2100px 900px\"\r\n\r\n        // Number of pixels to move the parallax background per slide\r\n        // - Calculated automatically unless specified\r\n        // - Set to 0 to disable movement along an axis\r\n        parallaxBackgroundHorizontal: null,\r\n        parallaxBackgroundVertical: null,\r\n\r\n        // Options which are passed into marked\r\n        // See https://github.com/chjj/marked#options-1\r\n        markdown: {\r\n          smartypants: true\r\n        },\r\n\r\n        dependencies: [\r\n          // Cross-browser shim that fully implements classList - https://github.com/eligrey/classList.js/\r\n          { src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },\r\n\r\n          // Interpret Markdown in <section> elements\r\n          { src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },\r\n          { src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },\r\n\r\n          // Syntax highlight for <code> elements\r\n          { src: 'plugin/highlight/highlight.js', async: true, callback: function() { hljs.initHighlightingOnLoad(); } },\r\n\r\n          // Zoom in and out with Alt+click\r\n          { src: 'plugin/zoom-js/zoom.js', async: true },\r\n\r\n          // Speaker notes\r\n          { src: 'plugin/notes/notes.js', async: true },\r\n\r\n          // MathJax\r\n          { src: 'plugin/math/math.js', async: true }\r\n        ],\r\n\r\n      });\r\n\r\n    //-\r\n    script.\r\n      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){\r\n      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\r\n      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\r\n      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');\r\n\r\n      ga('create', 'UA-72531610-1', 'auto');\r\n      ga('send', 'pageview');\r\n\r\n");
}
}